apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  schedulerName: my-scheduler
  containers:
  - name: alpine
    image: alpine
    imagePullPolicy: IfNotPresent
    command:
    - "sh"
    - "-c"
    - >
      while true; do
        sleep 3600;
      done
